/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedStandingsRouteImport } from './routes/_authenticated/standings'
import { Route as AuthenticatedSlotsRouteImport } from './routes/_authenticated/slots'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedTournamentsIndexRouteImport } from './routes/_authenticated/tournaments.index'
import { Route as AuthenticatedTournamentsIdRouteImport } from './routes/_authenticated/tournaments.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandingsRoute = AuthenticatedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlotsRoute = AuthenticatedSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTournamentsIndexRoute =
  AuthenticatedTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTournamentsIdRoute =
  AuthenticatedTournamentsIdRouteImport.update({
    id: '/tournaments/$id',
    path: '/tournaments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/slots': typeof AuthenticatedSlotsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments/': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/slots': typeof AuthenticatedSlotsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/slots': typeof AuthenticatedSlotsRoute
  '/_authenticated/standings': typeof AuthenticatedStandingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/_authenticated/tournaments/': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/settings'
    | '/slots'
    | '/standings'
    | '/teams'
    | '/upload'
    | '/tournaments/$id'
    | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/settings'
    | '/slots'
    | '/standings'
    | '/teams'
    | '/upload'
    | '/tournaments/$id'
    | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/_authenticated/slots'
    | '/_authenticated/standings'
    | '/_authenticated/teams'
    | '/_authenticated/upload'
    | '/_authenticated/tournaments/$id'
    | '/_authenticated/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standings': {
      id: '/_authenticated/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedStandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slots': {
      id: '/_authenticated/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AuthenticatedSlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/': {
      id: '/_authenticated/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AuthenticatedTournamentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/$id': {
      id: '/_authenticated/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSlotsRoute: typeof AuthenticatedSlotsRoute
  AuthenticatedStandingsRoute: typeof AuthenticatedStandingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedTournamentsIdRoute: typeof AuthenticatedTournamentsIdRoute
  AuthenticatedTournamentsIndexRoute: typeof AuthenticatedTournamentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSlotsRoute: AuthenticatedSlotsRoute,
  AuthenticatedStandingsRoute: AuthenticatedStandingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedTournamentsIdRoute: AuthenticatedTournamentsIdRoute,
  AuthenticatedTournamentsIndexRoute: AuthenticatedTournamentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
